<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.systemdesign.ticketmaster</groupId>
        <artifactId>ticketmaster</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>booking-aggregator</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>api</module>
        <module>shared</module>
        <module>admission</module>
        <module>reservation</module>
        <module>checkout</module>
        <module>payment</module>
        <module>infrastructure</module>
        <module>tests</module>
        <module>architecture</module>
        <module>bootstrap</module>
    </modules>
</project>
