<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.systemdesign.ticketmaster</groupId><artifactId>booking-aggregator</artifactId><version>0.0.1-SNAPSHOT</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>booking-api</artifactId>
    <dependencies>
        <dependency><groupId>org.springframework</groupId><artifactId>spring-web</artifactId></dependency>
        <dependency><groupId>org.springframework</groupId><artifactId>spring-context</artifactId></dependency>
        <dependency><groupId>jakarta.validation</groupId><artifactId>jakarta.validation-api</artifactId></dependency>
        <dependency><groupId>jakarta.annotation</groupId><artifactId>jakarta.annotation-api</artifactId></dependency>
        <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-annotations</artifactId></dependency>
        <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId></dependency>
    </dependencies>
    <build><plugins><plugin>
        <groupId>org.openapitools</groupId><artifactId>openapi-generator-maven-plugin</artifactId><version>${openapi.generator.version}</version>
        <executions><execution><goals><goal>generate</goal></goals><configuration>
            <inputSpec>${project.basedir}/src/main/resources/openapi.yaml</inputSpec>
            <generatorName>spring</generatorName>
            <apiPackage>com.systemdesign.ticketmaster.booking.api</apiPackage>
            <modelPackage>com.systemdesign.ticketmaster.booking.api.model</modelPackage>
            <generateSupportingFiles>false</generateSupportingFiles>
            <configOptions>
                <interfaceOnly>true</interfaceOnly><skipDefaultInterface>true</skipDefaultInterface>
                <useSpringBoot3>true</useSpringBoot3><useJakartaEe>true</useJakartaEe>
                <openApiNullable>false</openApiNullable><documentationProvider>none</documentationProvider>
                <annotationLibrary>none</annotationLibrary><useTags>true</useTags>
            </configOptions>
        </configuration></execution></executions>
    </plugin></plugins></build>
</project>
