<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.systemdesign.ticketmaster</groupId><artifactId>search-infrastructure-aggregator</artifactId><version>0.0.1-SNAPSHOT</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>search-infrastructure-input</artifactId>
    <dependencies>
        <dependency><groupId>com.systemdesign.ticketmaster</groupId><artifactId>search-api</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.systemdesign.ticketmaster</groupId><artifactId>search-domain</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.systemdesign.ticketmaster</groupId><artifactId>search-application</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.systemdesign.ticketmaster</groupId><artifactId>search-infrastructure-common</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-actuator</artifactId></dependency>
        <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
        <dependency><groupId>org.assertj</groupId><artifactId>assertj-core</artifactId><scope>test</scope></dependency>
    </dependencies>
</project>
